### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by amitava82** [pranav-bharadwaj/Todo-app#1]
https://github.com/pranav-bharadwaj/Todo-app/blob/cd2883101268950d4fbd2eaa2f409192083dc01e/.env#L1

You're exposing admin secret which gives access to db. How do you fix it?

**Comment by amitava82** [comment]
@pranav-bharadwaj How do you think you'll fix it?

**Comment by pranav-bharadwaj** [comment]
Sorry sir, I just forget to include .env in .gitignore. Now it's fixed.

**Comment by amitava82** [comment]
No, that does not fix it. I can look at your network request and get access to the token. The solution is not to use the secret and use Hasura access control

**Comment by pranav-bharadwaj** [comment]
Ok sir thank you for reviewing web application,I thought that you are asking me about .env file is exposed to publicly how to fix it.Surely I will fix it on web app.
